repositories:
- name: ingress-nginx
  url: "https://kubernetes.github.io/ingress-nginx"
- name: cert-manager
  url: "https://charts.jetstack.io"
- name: metrics-server
  url: "https://kubernetes-sigs.github.io/metrics-server/"

releases:
  - name: ingress-nginx
    namespace: ingress-nginx                  
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    version: 4.8.1
  - name: cert-manager
    namespace: cert-manager                 
    createNamespace: true
    chart: jetstack/cert-manager
    version: v1.13.1
  - name: metrics-server
    namespace: metrics-server               
    createNamespace: true
    chart: metrics-server/metrics-server
    version: 3.11.0
  - name: syndicate
    chart: ./django-demo
    values:
      - ./helm-values/django-demo/values.yaml
      - ./helm_secrets/django_config.yaml
      - ./helm_secrets/django_secret.yaml