{{- if .Values.networkPolicy.create -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ include "django-demo.namespace" . }}
  name: {{ include "django-demo.fullname" . }}
  labels:
    {{- include "django-demo.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "django-demo.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.types | nindent 4 }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
{{- end }}