apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "django-demo.namespace" . }}
  labels:
    {{- toYaml .Values.namespaceLabels | nindent 4 }}
    {{- include "django-demo.labels" . | nindent 4 }}